# CMake generated Testfile for 
# Source directory: /home/meggie/文档/hotness_aware_leveldb
# Build directory: /home/meggie/文档/hotness_aware_leveldb/hoard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/home/meggie/文档/hotness_aware_leveldb/hoard/c_test")
add_test(fault_injection_test "/home/meggie/文档/hotness_aware_leveldb/hoard/fault_injection_test")
add_test(issue178_test "/home/meggie/文档/hotness_aware_leveldb/hoard/issue178_test")
add_test(issue200_test "/home/meggie/文档/hotness_aware_leveldb/hoard/issue200_test")
add_test(env_test "/home/meggie/文档/hotness_aware_leveldb/hoard/env_test")
add_test(status_test "/home/meggie/文档/hotness_aware_leveldb/hoard/status_test")
add_test(no_destructor_test "/home/meggie/文档/hotness_aware_leveldb/hoard/no_destructor_test")
add_test(autocompact_test "/home/meggie/文档/hotness_aware_leveldb/hoard/autocompact_test")
add_test(corruption_test "/home/meggie/文档/hotness_aware_leveldb/hoard/corruption_test")
add_test(db_test "/home/meggie/文档/hotness_aware_leveldb/hoard/db_test")
add_test(dbformat_test "/home/meggie/文档/hotness_aware_leveldb/hoard/dbformat_test")
add_test(filename_test "/home/meggie/文档/hotness_aware_leveldb/hoard/filename_test")
add_test(log_test "/home/meggie/文档/hotness_aware_leveldb/hoard/log_test")
add_test(recovery_test "/home/meggie/文档/hotness_aware_leveldb/hoard/recovery_test")
add_test(skiplist_test "/home/meggie/文档/hotness_aware_leveldb/hoard/skiplist_test")
add_test(chunklog_test "/home/meggie/文档/hotness_aware_leveldb/hoard/chunklog_test")
add_test(version_edit_test "/home/meggie/文档/hotness_aware_leveldb/hoard/version_edit_test")
add_test(version_set_test "/home/meggie/文档/hotness_aware_leveldb/hoard/version_set_test")
add_test(write_batch_test "/home/meggie/文档/hotness_aware_leveldb/hoard/write_batch_test")
add_test(nvmwrite_batch_test "/home/meggie/文档/hotness_aware_leveldb/hoard/nvmwrite_batch_test")
add_test(chunktable_test "/home/meggie/文档/hotness_aware_leveldb/hoard/chunktable_test")
add_test(nvmtable_test "/home/meggie/文档/hotness_aware_leveldb/hoard/nvmtable_test")
add_test(memenv_test "/home/meggie/文档/hotness_aware_leveldb/hoard/memenv_test")
add_test(filter_block_test "/home/meggie/文档/hotness_aware_leveldb/hoard/filter_block_test")
add_test(table_test "/home/meggie/文档/hotness_aware_leveldb/hoard/table_test")
add_test(arena_test "/home/meggie/文档/hotness_aware_leveldb/hoard/arena_test")
add_test(bloom_test "/home/meggie/文档/hotness_aware_leveldb/hoard/bloom_test")
add_test(cache_test "/home/meggie/文档/hotness_aware_leveldb/hoard/cache_test")
add_test(coding_test "/home/meggie/文档/hotness_aware_leveldb/hoard/coding_test")
add_test(crc32c_test "/home/meggie/文档/hotness_aware_leveldb/hoard/crc32c_test")
add_test(hash_test "/home/meggie/文档/hotness_aware_leveldb/hoard/hash_test")
add_test(logging_test "/home/meggie/文档/hotness_aware_leveldb/hoard/logging_test")
add_test(multi_bloomfilter_test "/home/meggie/文档/hotness_aware_leveldb/hoard/multi_bloomfilter_test")
add_test(env_posix_test "/home/meggie/文档/hotness_aware_leveldb/hoard/env_posix_test")
